AWSTemplateFormatVersion: '2010-09-09'
Description: 'Static website hosting with S3, CloudFront, and SSL certificate with proper DNS validation'

Parameters:
  DomainName:
    Type: String
    Description: 'Your custom domain name (e.g., yourdomain.com)'
    AllowedPattern: '^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$'
    ConstraintDescription: 'Must be a valid domain name'

  SubdomainName:
    Type: String
    Description: 'Subdomain for the website (e.g., www)'
    Default: 'www'
    AllowedPattern: '^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$'

  EnableSSL:
    Type: String
    Description: 'Enable SSL certificate and custom domain'
    Default: 'false'
    AllowedValues: ['true', 'false']

  CertificateValidationMethod:
    Type: String
    Description: 'Certificate validation method'
    Default: 'DNS'
    AllowedValues: ['DNS', 'EMAIL']

Conditions:
  UseSSL: !Equals [!Ref EnableSSL, 'true']
  UseDNSValidation: !And
    - !Condition UseSSL
    - !Equals [!Ref CertificateValidationMethod, 'DNS']

Resources:
  # Route 53 Hosted Zone (always created for DNS management)
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone for ${DomainName}'

  # S3 Bucket for website hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-${SubdomainName}-${DomainName}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3600
      VersioningConfiguration:
        Status: Enabled

  # S3 Bucket Policy
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket}/*'

  # SSL Certificate (conditional)
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: UseSSL
    Properties:
      DomainName: !Sub '${SubdomainName}.${DomainName}'
      SubjectAlternativeNames:
        - !Ref DomainName
      ValidationMethod: !Ref CertificateValidationMethod
      DomainValidationOptions: !If
        - UseDNSValidation
        - - DomainName: !Sub '${SubdomainName}.${DomainName}'
            HostedZoneId: !Ref HostedZone
          - DomainName: !Ref DomainName
            HostedZoneId: !Ref HostedZone
        - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ssl-certificate'

  # CloudFront Origin Access Control
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${AWS::StackName}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: !If
          - UseSSL
          - - !Sub '${SubdomainName}.${DomainName}'
            - !Ref DomainName
          - !Ref AWS::NoValue
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: !If [UseSSL, 'redirect-to-https', 'allow-all']
          CachePolicyId: '658327ea-f89d-4fab-a63d-7e88639e58f6' # Managed-CachingOptimized
          OriginRequestPolicyId: '88a5eaf4-2fd4-4709-b370-b4c650ea3fcf' # Managed-CORS-S3Origin
          ResponseHeadersPolicyId: '67f7725c-6f97-4210-82d7-5512b31e9d03' # Managed-SecurityHeadersPolicy
          Compress: true
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref OriginAccessControl
        PriceClass: PriceClass_100
        ViewerCertificate: !If
          - UseSSL
          - AcmCertificateArn: !Ref SSLCertificate
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  # Route 53 Records (conditional - only when SSL is enabled)
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Condition: UseSSL
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub '${SubdomainName}.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: 'Z2FDTNDATAQYW2' # Global CloudFront hosted zone ID

  DNSRecordRoot:
    Type: AWS::Route53::RecordSet
    Condition: UseSSL
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: 'Z2FDTNDATAQYW2' # Global CloudFront hosted zone ID

Outputs:
  WebsiteURL:
    Description: 'Website URL'
    Value: !If
      - UseSSL
      - !Sub 'https://${SubdomainName}.${DomainName}'
      - !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

  CloudFrontURL:
    Description: 'CloudFront Distribution URL (always accessible)'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontURL'

  S3BucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'

  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  HostedZoneId:
    Description: 'Route 53 Hosted Zone ID'
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'

  NameServers:
    Description: 'Name servers for your domain (configure these in Namecheap)'
    Value: !Join [', ', !GetAtt HostedZone.NameServers]
    Export:
      Name: !Sub '${AWS::StackName}-NameServers'

  SSLCertificateArn:
    Condition: UseSSL
    Description: 'SSL Certificate ARN'
    Value: !Ref SSLCertificate
    Export:
      Name: !Sub '${AWS::StackName}-SSLCertificateArn'

  SSLCertificateStatus:
    Condition: UseSSL
    Description: 'SSL Certificate validation status'
    Value: 'Certificate created - check AWS Certificate Manager for validation status'
